#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="traefik-pihole-companion"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting Traefik PiHole Companion"
exec s6-setuidgid "${TCC_USER}" \
                                python3 \
                                        -u /usr/sbin/pihole-companion
