services:
  cloudflare-companion:
    image: domscott/traefik-pihole-companion
    container_name: pihole-companion
    volumes:
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEZONE=America/Vancouver

      - LOG_TYPE=BOTH
      - LOG_LEVEL=INFO

      - TRAEFIK_VERSION=2
      - PH_URL=email@example.com
      - PH_TOKEN=fbSx3dk3A3mJ6UukLQ7zRbo63H5UdsGSCqQnTvbJDgyQaTp
      - TARGET_IP=192.168.1.2
      - DOMAIN1=example.org

      #- DOCKER_HOST=tcp://198.51.100.32:2376
      #- DOCKER_CERT_PATH=/docker-certs
      #- DOCKER_TLS_VERIFY=1

      #- TRAEFIK_FILTER_LABEL=traefik.constraint
      #- TRAEFIK_FILTER=proxy-public
    networks:
      - services
    restart: always

networks:
  services:
    external: true
